### ISSUE TITLE
More recent (upstream) kernel for SiFive Unleashed board?

### ISSUE THREAD

**Issue by laanwj** [rwmjones/fedora-riscv-kernel#4]
It would be nice to have more recent kernels for Fedora RISC-V, even if just for testing before going back to the old "stable" one.

However I've tried to get this to work to build more recent kernels, but had very little luck (I've documented some steps here with regard to 5.0.x: https://forums.sifive.com/t/linux-5-0-on-hifive-unleashed/2174 )

**Comment by rwmjones** [comment]
This repo is really just a temporary thing.  David A. is already building Fedora kernels as RPMs, and once we have the bootloader chain sorted out properly we will be able to use those.

**Comment by laanwj** [comment]
Ok, thanks.
Prebuilt RPM kernels would be great for me.

Edit: FWIW for anyone stumbling on this, I did eventually get Linux 5.1 to work on the board with only minimal changes to this, see the forums link above.
